program _if; //by Rudyard Kipling, 1943
begin
	writeln('if by Reduard Kipling');
	readln;
	writeln('If you can keep your head when all about you');
	readln;
	writeln('Are losing theirs and blaming it on you,');
	readln;
	writeln('If you can trust yourself when all men doubt you,');
	readln;
	writeln('But make allowance for their doubting too;');
	readln;
	writeln('If you can wait and not be tired by waiting,');
	readln;
	writeln('Or being lied about, don`t deal in lies,');
	readln;
	writeln('Or being hated, don`t give way to hating,');
	readln;
	writeln('And yet don`t look too good, nor talk too wise:');
	readln;
	writeln('If you can dream - and not make dreams your master;');
	readln;
	writeln('If you can think - and not make thoughts your aim;');
	readln;
	writeln('If you can meet with Triumph and Disaster');
	readln;
	writeln('And treat those two impostors just the same;');
	readln;
	writeln('If you can bear to hear the truth you`ve spoken');
	readln;
	writeln('Twisted by knaves to make a trap for fools,');
	readln;
	writeln('Or watch the things you gave your life to, broken,');
	readln;
	writeln('And stoop and build`em up with worn-out tools:');
	readln;
	writeln('If you can make one heap of all your winnings');
	readln;
	writeln('And risk it on one turn of pitch-and-toss,');
	readln;
	writeln('And lose, and start again at your beginnings');
	readln;
	writeln('And never breathe a word about your loss;');
	readln;
	writeln('If you can force your heart and nerve and sinew');
	readln;
	writeln('To serve your turn long after they are gone,');
	readln;
	writeln('And so hold on when there is nothing in you');
	readln;
	writeln('Except the Will which says to them: `Hold on!`');
	readln;
	writeln('If you can talk with crowds and keep your virtue,');
	readln;
	writeln('Or walk with Kings - nor lose the common touch,');
	readln;
	writeln('If neither foes nor loving friends can hurt you,');
	readln;
	writeln('If all men count with you, but none too much;');
	readln;
	writeln('If you can fill the unforgiving minute');
	readln;
	writeln('With sixty seconds` worth of distance run,');
	readln;
	writeln('Yours is the Earth and everything that`s in it,');
	readln;
	writeln('And - which is more - you`ll be a Man, my son!')
end.

